server:
  port: 8762
eureka:
  instance:
    hostname: slave2
    lease-expiration-duration-in-seconds: 10
#    prefer-ip-address: true
  client:
#    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://slave1:8761/eureka/
  server:
    enable-self-preservation: false
spring:
  application:
    name: server